---
# tasks file for pDBServer
- name: Install Postgres
  yum:
    name: postgresql-server
    state: latest

- name: Check If Postgres DB is Initialized
  command: ls -ltr /var/lib/pgsql/data/
  register: pgdata_files  
    
- name: Initialize Postgres
  command: postgresql-setup initdb
  when: pgdata_files.stdout == ""

- name: start postgres
  service:
    name: postgresql
    state: started
    enabled: yes
...
